### ISSUE TITLE
Maximum of 5 client sessions

### ISSUE THREAD

**Issue by chiu-sg** [martin-ger/uMQTTBroker#12] opened 2018-04-26 16:08 UTC
Hi Martin,

Firstly, I would like to thank you for the awesome work you've put into this library. Thumbs up!

I've loaded a nodeMCU with this code and it is working as the MQTT broker for my automation project. I've also flashed a few Sonoff S20 plugs with the [Tasmota](https://github.com/arendst/Sonoff-Tasmota) firmware and have successfully connected them to the broker and controlled their relay state with the correct MQTT message. 

However while testing the plug (turning their power on/off to simulate reconnections to the broker), I've realised that on the 5th reset of a single plug, I was no longer able to connect it back to the broker. The Sonoff web console shows a rc=-4 error which refers to a MQTT_CONNECTION_TIMEOUT in the pubsubclient MQTT library. The broker is still running just that it is no longer accepting any new client connection. The last message received was the LWT offline message of the disconnected switch.

I've tried to replicate the issue by running 5 clients on a MQTTBox simulator and as I tried to connect the 5th client, the connection could not get through.

Has the nodeMCU broker reached its connection or memory limit or is there some configuration which I can change to rectify this problem?

Your help is very much appreciated. TIA!

**Comment by martin-ger** [comment] 2018-04-27 05:38
Are you using the ESP as AP? There is a defaulf of max 4 connected STAs.

**Comment by martin-ger** [comment] 2018-04-27 06:29
Okay, I remember, there is another limit. Use:
```
extern "C" {
  #include "espconn.h"
}
```
and
`espconn_tcp_set_max_con(8);`

https://github.com/esp8266/Arduino/issues/3185

**Comment by chiu-sg** [comment] 2018-04-27 07:11
Thanks for your reply Martin.

I've tried adding the above codes into the program but it does not solve the issue. I've read more into the link you've provided above and I think the max connections only apply when the ESP is in AP mode?

I think the problem I am facing is related to proper closing of offline connections instead of max connections as with 0 live clients online, I am also not able to connect any new client to the broker if I've previously connected and disconnected 5 clients.

**Comment by martin-ger** [comment] 2018-04-29 20:45
Some issues - questions:

How do you close the connections? 

What happens, if you wait some seconds (minutes)? This frees TCP connections in TIMEWAIT.

espconn_tcp_set_max_con(8); really applies to all kind of network connections - it is the number of max concurrent TCP connections.

**Comment by MunteanuE** [comment] 2018-05-18 14:40
I confirm that there is a issue regarding the number of connections. The 6th attempt to connect to the broker fails and there is no any rejection log at all.  espconn_tcp_set_max_con(8) doesn't help.... just try to connect and disconnect 6 times. 
I tried also to clean up connection **MQTT_server_cleanupClientCons** periodically, but no results.

**Comment by martin-ger** [comment] 2018-05-18 16:14
Hmm, cannot reproduce this - at least not with mqtt-spy as client. I can connect/disconnect as often, as I like...

What client SW do you use? Any sketch you can share with me?

**Comment by MunteanuE** [comment] 2018-05-18 16:27
The Sketch is brokerSample
The client is mqtt buddy And others. But usually many clients doesn’t work properly with Mqtt 3.1.1. So I configured the library to work with ver. 3.1. Thanks for fast response.

**Comment by RudyFiero** [comment] 2018-05-18 17:11
@MunteanuE Can you tell me the specific lines that you are changing to try and get more than 6 connections. I have a number of ESP8266 that I can set up for this test, along with MQTT Spy.

**Comment by RudyFiero** [comment] 2018-05-18 17:39
Sorry but I wasn't clear. I meant what changes did you make to increase the number of clients?  Is this all that you did?

```
extern "C" {
  #include "espconn.h"
}
and
espconn_tcp_set_max_con(8);
```

**Comment by MunteanuE** [comment] 2018-05-18 17:46
I tried also to increase the number of clients as you mentioned but with no effect

**Comment by MunteanuE** [comment] 2018-05-18 19:09
I had time to test the BrokerSample this evening with **PROTOCOL_NAMEv311** and with `espconn_tcp_set_max_con(8);`. The MQTT client was [MQTT-spy](https://github.com/eclipse/paho.mqtt-spy/releases/download/1.0.0/mqtt-spy-1.0.0.jar).
The problem is persistent, the 6th attempt to reconnect to broker fails. You don't need 6 devices to check it, just connect and disconnect  to broker 6 times.
I'm almost sure that the problem is with disconnecting of clients ( `MQTT_ClientCon_discon_cb ` or espconn_disconnect from  `void ICACHE_FLASH_ATTR MQTT_ServerTask(os_event_t * e)`)

**Comment by martin-ger** [comment] 2018-05-18 19:28
Did some research here:

Setup: an external AP, one ESP connected to it running the uMQTTBroker (or my esp_mqtt that uses exactly the same uMQTTBroker but has a lot more runtime debugging) and a Linux machine with mqtt-spy and an Android Phone with MQTT Buddy.

Results: 
- no problems with connecting and disconnection one MQTT session with mqtt-spy as often as I want
- MQTT Buddy is difficult: looked into wireshark traces:
  * when going to standby it holds the old session first, than tries to close it and
  * when waking up again, it floods the ESP with strange disconnect packets
  * this consumes all mem in the ESP and prevents establishment of a new session (no mem)

**Comment by martin-ger** [comment] 2018-05-18 19:42
An Android client that behaves absolutely well in contrast is the "MQTT Dashboard" - again no problem in connecting and reconnecting as often as I like...

Please make sure, you are using the latest version of uMQTTBroker. Versions before Jan 25. had a known problem in special disconnect sequences...

**Comment by MunteanuE** [comment] 2018-05-18 20:39
@martin-ger  I had the same problem with "MQTT Dashboard" - after pausing of the application (staying in background for a while) the connection to broker is dropped, so after resuming application it reconnects again. Try this 6 times. The short cut is just to kill the "MQTT Dashboard" and relaunch it again. May be you didn't reconnect properly (you haven't a lost connection).

**Comment by martin-ger** [comment] 2018-05-19 04:55
Yes, it also drops the connection - but it reconnects properly as often as I like (at lleast for me) and doesn't flood the ESP with nonsense packets....

Let me try to reproduce it - some questions:
1) Do you use the latest version of the lib?
2) Do you have the same setup (external AP, one ESP connected to it running the uMQTTBroker)?
3) Could you try the esp_mqtt binaries with your setup? (https://github.com/martin-ger/esp_mqtt/tree/master/firmware - here you can see with "show mqtt" and "show stats" the currently connected clients and the mem status)

**Comment by martin-ger** [comment] 2018-05-19 05:16
Other guess - if case 3. shows a different (better) behaviour, maybe it is a problem with lwip2 in the new Arduino core? I still have installed an Arduino environment with the original 1.4 lwip...

There are several reports on a "disconnection/reconnection issue" in Arduino core 2.4 (claims to be fixed in version 2.4.2)

**Comment by martin-ger** [comment] 2018-05-19 06:51
One more question:  does it help, if you wait some time (1 minute or so) before trying it again? Guess is: state TCP_TIMEWAIT...

**Comment by RudyFiero** [comment] 2018-05-19 09:08
I reinstalled this library. I am running git from a few days ago. I am using MQTT Spy as the client. I monitored the traffic with Wireshark.

I reset the broker. 

I connected with MQTT Spy. I subscribed to a test message. I published one test message. I then closed the MQTT Spy session connection. 

I then did the same sequence of the above (below resetting the broker) successfully four more times. 

On the sixth time it did not establish a connection.  If it is of any help I have attached a zip file that contains the Wireshark file. 

[uBroker.zip](https://github.com/martin-ger/uMQTTBroker/files/2019287/uBroker.zip)

**Comment by martin-ger** [comment] 2018-05-19 09:49
Okay, thanks a lot. This helps a little bit to trace it down: in packets 92-97 is the first unsuccessful connect request. Here the ESP actively resets (RST) the connection after the successful three-way handshake. Do not understand why, but we are coming closer.

Could you try the same and reconnect some time later (a minute or so)?

**Comment by martin-ger** [comment] 2018-05-19 09:58
Does it change anything if you replace
espconn_disconnect(
with 
espconn_abort(
in line mqtt_server.c:890

Somewhat brutal, but it might free the resources...

**Comment by MunteanuE** [comment] 2018-05-19 10:34
Here is the log file for one client without publishing, maybe it will be helpful
[broker.log](https://github.com/martin-ger/uMQTTBroker/files/2019348/broker.log)
.

**Comment by martin-ger** [comment] 2018-05-19 11:08
Thanks - looked into it: exactly the sequence I would expect - ends with a proper "disconnect" in the main task for each connection. Afterwards the (new ?) lwip stack rejects any new connection...

Think, I will have to install the lastest Arduino an try to debug into the stack...

**Comment by martin-ger** [comment] 2018-05-19 13:40
Okay, got it! It's the lwip 2.0!

Installed the latest Arduino core and with default settings I get exactly the behavior you describe: block after five connections.

Switched back to "Lwip Variant 1.4 High Bandwidth" in the "Tools" menu - works!

So, I still do not understand, why it fails, but it seems to be an lwip 2.0 issue...

**Comment by MunteanuE** [comment] 2018-05-19 20:02
Yes, it works like a charm with **lwip 1.4** !
Thank you @martin-ger !

**Closed** 2018-05-20 06:04 UTC

**Comment by d-a-v** [comment] 2019-06-23 01:11
Hi,

I just discovered this great library.
About lwip2 not working the reason is simple: this library historically uses `espconn` which is an espressif derivative of lwIP's (obsolete) `netconn`.
Rewriting the network part using `ESP8266WiFi` would add these benefits:
- use lwIP-v2 (more stable)
- allow SSL (thanks to BearSSL from WiFiClientSecure)
- allow more than 5 simultaneous connections

This is feasible but requires however some time because of the whole structure based on network events.

**Comment by martin-ger** [comment] 2019-07-22 10:17
Just saw that - yes rewriting it without espconn is a major effort. I probably won't do that. An if so, I would probably go directly for the ESP32 as is costs only a little bit more and has enough memory for a broker.

**Comment by RudyFiero** [comment] 2019-07-22 14:11
An ESP32 version would be **fantastic!**
